#!/bin/bash

mvn install

hdfs dfs -rm -r input

hdfs dfs -rm -r out

hadoop fs -copyFromLocal datasets/ input

hadoop jar ./target/nSearch-1.0.jar input/noticias.csv out cássio 495ad7ba-2c0e-492e-aa64-f3d4f86049a0 local

#rm -r out*

hdfs dfs -copyToLocal out out$(date +%s)

#hadoop jar ./target/bdp-1.0.jar dataSet1.txt $(date +%s)